version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80" # HTTP 트래픽을 위한 포트
      - "443:443" # HTTPS 트래픽을 위한 포트
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certificates:/etc/nginx/certificates
    depends_on:
      - react-app
      - nest-app
    networks:
      - app-network
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email tkacnsdms1@gmail.com -d http://recipesoup.koreacentral.cloudapp.azure.com --agree-tos
    
  react-app:
    container_name: react-app
    image: runninglearner/recipesoup:latest # Docker Hub에서 가져올 이미지
    ports:
      - "3000:3000"
    env_file:
      - frontend.env
    networks:
      - app-network

  nest-app:
    container_name: nest-app
    image: runninglearner/recipesoupapi:latest # Docker Hub에서 가져올 이미지
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/usr/src/app/logs
    env_file:
      - backend.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: recipesoup
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
