version: "3.8"
services:
  react-app:
    container_name: react-app
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  nest-app:
    container_name: nest-app
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./back:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: recipesoup
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./back/init_sql:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
